/*HACER USO DE LA BASE DE DATOS*/
use FyM_project_db;

/*EJECUTAR EL PROCEDIMIENTO ALMACENADO INGRESAR_CARGO PARA ALMACENAR LOS DATOS SUMINISTRADOS EN LA TABLA CORRESPONDIENTE*/
/*values(cargo)*/
execute ingresar_cargo 'Auxiliar de bodéga';

/*EJECUTAR EL PROCEDIMIENTO ALMACENADO INGRESAR_EMPLEADO PARA ALMACENAR LOS DATOS SUMINISTRADOS EN LA TABLA CORRESPONDIENTE*/
/*values(num_doc, nom_1, nom_2, ape_1, ape_2, cargo, sueldo, email, direccion, telefono)*/
execute ingresar_empleado 1042459195, 'Stefany', 'Carolina', 'Muñoz', 'Ortiz', 2, 1500000, 'stefany_cmo@hotmail.com', 'Cra 56 b # 87a 26', 3222762625;

/*EJECUTAR EL PROCEDIMIENTO ALMACENADO INGRESAR_AREA PARA ALMACENAR LOS DATOS SUMINISTRADOS EN LA TABLA CORRESPONDIENTE*/
/*values(area)*/
execute ingresar_area 'Bodéga';

/*EJECUTAR EL PROCEDIMIENTO ALMACENADO INGRESAR_AREA_EMPLEADO PARA ALMACENAR LOS DATOS SUMINISTRADOS EN LA TABLA CORRESPONDIENTE*/
/*values(area, empleado)*/
execute ingresar_area_empleado 1, 1003764503;

/*EJECUTAR EL PROCEDIMIENTO ALMACENADO INGRESAR_CONTENEDOR PARA ALMACENAR LOS DATOS SUMINISTRADOS EN LA TABLA CORRESPONDIENTE*/
/*values(tipo_contenedor, peso)*/
execute ingresar_contenedor 'Bolsa papel base cuadrada', 0.200;

/*EJECUTAR EL PROCEDIMIENTO ALMACENADO INGRESAR_PRODUCTO PARA ALMACENAR LOS DATOS SUMINISTRADOS EN LA TABLA CORRESPONDIENTE*/
/*values(producto, tipo_contenedor, peso, alergeno, precio, total_peso_almacenado, total_unds_almacenado)*/
execute ingresar_producto 'Maltodrextrina M100', 1, 25, 'NO', 500000, 0, 0;

/*EJECUTAR EL PROCEDIMIENTO ALMACENADO INGRESAR_INGRESO PARA ALMACENAR LOS DATOS SUMINISTRADOS EN LA TABLA CORRESPONDIENTE*/
/*values(fecha, empleado)*/
execute ingresar_ingreso '2023-04-11 12:00:00', 1003764503;

/*EJECUTAR EL PROCEDIMIENTO ALMACENADO INGRESAR_PRODUCTO_INGRESO PARA ALMACENAR LOS DATOS SUMINISTRADOS EN LA TABLA CORRESPONDIENTE*/
/*values(ingreso, producto, total_peso_ingresado, total_unds_ingresado)*/
execute ingresar_producto_ingresado 1, 1, 1000, 40;

/*EJECUTAR EL PROCEDIMIENTO ALMACENADO INGRESAR_VENTA PARA ALMACENAR LOS DATOS SUMINISTRADOS EN LA TABLA CORRESPONDIENTE*/
/*values(fecha, empleado)*/
execute ingresar_venta '2023-04-11 12:00:00', 1042459195;

/*EJECUTAR EL PROCEDIMIENTO ALMACENADO INGRESAR_PRODUCTO_VENDIDO PARA ALMACENAR LOS DATOS SUMINISTRADOS EN LA TABLA CORRESPONDIENTE*/
/*values(venta, producto, total_unds_vendido)*/
execute ingresar_producto_vendido 1, 1, 2;

/*EJECUTAR LA VISTA CONSULTAR_DATOS_EMPLEADO PARA CONSULTAR TODOS LOS CAMPOS DE LA TABLA EMPLEADO INLUYENDO EL NOMBRE DEL CARGO ASIGNADO EN LA TABLA CARGO*/
select * from consultar_datos_empleado;

/*EJECUTAR LA VISTA CONSULTAR_PRODUCTO PARA CONSULTAR LOS CAMPOS DE LA TABLA PRODUCTO INCLUYENDO EL NOMBRE DEL CONTENEDOR ASIGANO EN LA TABLA CONTENEDOR*/
select * from consultar_producto;

/*EJECUTAR LA VISTA CONSULTAR_CANTIDAD_PRODUCTO_ALMACENADO PARA CONSULTAR LA CANTIDAD TOTAL DE PESO Y UNIDADES EN STOCK*/
select * from consultar_cantidad_producto_almacenado;

/*EJECUTAR LA VISTA CONSULTAR_INGRESO PARA CONSULTAR LOS CAMPOS DE LA TABLA INGRESO INCLUYENDO EL NOMBRE Y APELLIDO DEL EMPLEADO ASIGANO EN LA TABLA EMPLEADO*/
select * from consultar_ingreso;

/*EJECUTAR LA VISTA CONSULTAR_INGRESO_PRODUCTO PARA CONSULTAR LOS CAMPOS DE LA TABLA PRODUCTO_INGRESADO INCLUYENDO EL NOMBRE DEL PRODUCTO INGRESADO ASIGANO EN LA TABLA PRODUCTO*/
select * from consultar_ingreso_producto;

/*EJECUTAR LA VISTA CONSULTAR_VENTA PARA CONSULTAR LOS CAMPOS DE LA TABLA VENTA INCLUYENDO EL NOMBRE Y APELLIDO DEL VENDEDOR ASIGANO EN LA TABLA EMPLEADO*/
select * from consultar_venta;

/*EJECUTAR LA VISTA CONSULTAR_VENTA_PRODUCTO PARA CONSULTAR LOS CAMPOS DE LA TABLA PRODUCTO_VENDIDO INCLUYENDO EL NOMBRE DEL PRODUCTO INGRESADO ASIGANO EN LA TABLA PRODUCTO*/
select * from consultar_venta_producto;
